name: Deployment
on:
  push:
    branches:
      - release

jobs:
  deploy:
    name: Deployment
    runs-on: self-hosted
    steps:
        - run: "echo TODO: todo"
#       - run: |
#           cd ${{ secrets.APP_ROOT }}
#           git checkout release
#           git fetch
#           git ff
#           pm2 restart -s ${{ secrets.PROCESS_NAME }}